### ISSUE TITLE
npm run plugin.tscwatch doesn't create platforms folder

### ISSUE THREAD

**Issue by DevPlus31** [NativeScript/nativescript-plugin-seed#103]
The npm run plugin.tscwatch command doesn't create platforms folder
and the result of npm run build returns 
No plugin found at the current directory, or the plugin does not need to have its platforms/android components built into an `.aar`

Am I missing something?

Thanks

**Comment by elena-p** [comment]
Hi @DevPlus31,

I apologise for the late response. 

`npm run plugins.tscwatch` command is NOT supposed to create plugin's platform folder. The command compiles your plugin's TypeScript code, and then remains running to watch for any subsequent changes you make to your plugin's source code. When the command detects changes, it'll compile your plugin's TypeScript to JavaScript automatically.

`build` script defined in `/src/package.json` calls the `build.native` script, which builds .arr in `platforms/android` folder. 

It seems that you have deleted the `/src/platforms/android` folder and that's causing the build error. You can either:
- Restore `/src/platforms/android` folder and use it for your plugin's [android permissions and resources](https://docs.nativescript.org/plugins/plugin-reference#android-permissions-and-resources)
or 
- If you DON'T have any [android permissions and resources](https://docs.nativescript.org/plugins/plugin-reference#android-permissions-and-resources) in your plugin, you can update the `build` script in `/src/package.json` to `npm i && npm run tsc`
