### ISSUE TITLE
Wrong Travis configuration

### ISSUE THREAD

**Issue by jdnichollsc** [NativeScript/nativescript-plugin-seed#130]
Hey guys,

I'm having some issues building from Travis:

1. A lot of TypeScript warnings `Namespace 'android' has no exported member 'content'.` It looks like you need to include `npm install` from `tsc` script of the package.json as you can see here => https://github.com/NativeScript/marketplace-feedback/issues/160#issuecomment-490431480

TEMPORAL SOLUTION: `"tsc": "npm install && tsc",`

2. `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.` After running this script => `android-wait-for-emulator`, Check the logs here: https://travis-ci.org/proyecto26/nativescript-inappbrowser/jobs/529916601

Investigating to fix this configuration...

**Comment by VladimirAmiorkov** [comment]
Hi @jdnichollsc ,

The issue has been resolve and is already in the master branch. You can apply the fix as you described it shown [here](https://github.com/NativeScript/nativescript-plugin-seed/blob/e1a8573dd4a72d89cd50fbf2e9297e3fe92dd058/src/package.json#L18).
