### ISSUE TITLE
Breakpoints in the plugin are not hit

### ISSUE THREAD

**Issue by adrian-niculescu** [NativeScript/nativescript-plugin-seed#139]
Tools used:
NativeScript: 5.4.0
NativeScript Extension for Visual Studio Code: 0.10.0

Create a plugin using this plugin seed, with a **TypeScript demo**.

The plugin code (`src/`) cannot be debugged using breakpoints since the addition of the "bundle workflow". This seems to be a Webpack configuration issue.
- webpack knows when a .js file in src/ is changed and the nativescript cli correctly syncs the app's bundle.
- with the current configuration **no Visual Studio Code breakpoints work** in `demo/node_modules/<plugin>/<file>.ts `(or `src/<file>.ts`).

**Comment by VladimirAmiorkov** [comment]
Hi @adrian-niculescu ,

Thank you for reporting this to us. Can you try to switch back to the legacy workflow that does not trigger `--bundle` and let us know if the break points are hit?

**Comment by adrian-niculescu** [comment]
With 
```
{
  "useLegacyWorkflow": true
}

```
it still does not work. 

I switched back to what I was using before:
The [5.1.0 release of this plugin seed](https://github.com/NativeScript/nativescript-plugin-seed/releases/tag/v.5.1.0) with nativescript 5.3.0. Breakpoints work as expected.
