### ISSUE TITLE
`demo-angular` does not build with tns 5.4.0

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-plugin-seed#140]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- Both 

### Please, provide the following version numbers that your issue occurs with:

- CLI: )5.4.0

### Please, tell us how to recreate the issue in as much detail as possible. 
After executing `cd src && npm run postclone` and accepting to create an Angular demo app, that demo app does not build after doing `tns run ios`

**Comment by zbranzov** [comment]
Fixed
