### ISSUE TITLE
Postclone script should replace "Your Plugin Name" reference in readme

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-plugin-seed#159]
The first heading should be automatically replaced with the with the name of the plugin. Also the reference to `<your-plugin-name>` in the `tns plugin add` section should also be replaced with the actual plugin.

**Comment by romulowspp** [comment]
I created a PR and I hope I'm doing what was proposed! : D

**Comment by zbranzov** [comment]
@romulowspp  Thanks for the PR and help provided to make NativesScript world better.
