### ISSUE TITLE
[Proposal] Remove publish folder/scripts

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-plugin-seed#164]
Looking at what the publish scripts are doing isn't it better to completely remove them and add appropriate scripts in the `package.json` file in the `src` folder. Then just execute `npm pack` or `npm publish` commands from inside the `src` folder. I think much more intuitive, not to mention that those `.sh` scripts cannot be execute under Windows 😉

**Comment by elena-p** [comment]
Duplicate of https://github.com/NativeScript/nativescript-plugin-seed/issues/77
