### ISSUE TITLE
Include images in plugin

### ISSUE THREAD

**Issue by brunoziie** [NativeScript/nativescript-plugin-seed#170]
I'm developing a plugin that need some images to compose the UI.
I tried to put the images at `src/platform/ios` and did not worked.

Is it possible?

**Comment by tgpetrov** [comment]
Hi @brunoziie 
It is possible, in order to make it work the images should be placed in `src/platforms/ios/Resources`.

**Comment by brunoziie** [comment]
thks, @tgpetrov
