### ISSUE TITLE
Publish script not working with NPM 5

### ISSUE THREAD

**Issue by DimitarTachev** [NativeScript/nativescript-plugin-seed#48]
Reported by sitefinitysteve in the community slack:
The publish script from the seed fails with "Cannot read property 'algorithm' of undefined" using NPM 5+.

**Comment by lini** [comment]
Issue is https://github.com/npm/npm/issues/16723
Already fixed and will be released next npm update.
We can also fix it if needed but the fix will not be elegant using the current pack & publish scripts.

**Comment by lini** [comment]
npm 5.6.0 is out. We should test to see if this is resolved.

**Comment by zbranzov** [comment]
I was not able to reproduce it using npm 5.6.
