### ISSUE TITLE
Packaging doesn't seem to be working

### ISSUE THREAD

**Issue by fhackenb** [NativeScript/nativescript-plugin-seed#67]
I have a plugin developed from the seed and I'm now at the point where I want to pull it into another app. Following the publish instructions, I was able to generate a nativescript-plugin-name-1.0.0.tgz file. When following the instructions to install it (tns plugin add nativescript-pluigin-name-1.0.0.tgz) after a minute or two of seemingly working it stops and tells me:

nativescript-plugin-name-1.0.0.tgz is not a valid NativeScript plugin. Verify that the plugin package.j
son file contains a nativescript key and try again. 

I unzipped the folder and checked it out and the package.json seems to have the same fields as in the seed plugin. Here it is:

{
    "name": "nativescript-plugin-name",
    "version": "1.0.0",
    "description": "Your awesome NativeScript plugin.",
    "main": "plugin-name",
    "typings": "index.d.ts",
    "nativescript": {
        "platforms": {
            "android": "3.0.0",
            "ios": "3.0.0"
        }
    },
    "scripts": {
        "tsc": "tsc -skipLibCheck",
        "postclone": "npm i && node scripts/postclone.js && cd ../demo && npm i && cd ../src && npm run plugin.link",
        "test.android": "npm i && npm run tsc && npm run tslint && cd ../demo && tns build android && tns test android --justlaunch",
        "test.ios": "npm i && npm run tsc && npm run tslint && cd ../demo && tns build ios && tns test ios --justlaunch",
        "tslint": "cd .. && tslint \"**/*.ts\" --config tslint.json --exclude \"**/node_modules/**\"",
        "plugin.link": "npm link && cd ../demo && npm link nativescript-ui-plugin && cd ../src",
        "plugin.tscwatch": "npm run tsc -- -w",
        "demo.ios": "npm i && npm run tsc && cd ../demo && tns run ios --syncAllFiles",
        "demo.android": "npm i && npm run tsc && cd ../demo && tns run android --syncAllFiles"
    },
    "keywords": [
        "NativeScript",
        "JavaScript",
        "Android",
        "iOS"
    ],
    "author": {
        "name": "Your Name",
        "email": "youremail@yourdomain.com"
    },
    "bugs": {
        "url": "https://github.com/YourName/nativescript-yourplugin/issues"
    },
    "license": "Apache-2.0",
    "homepage": "https://github.com/YourName/nativescript-yourplugin",
    "readmeFilename": "README.md",
    "peerDependencies": {
        "tns-core-modules": "^3.0.0"
    },
    "devDependencies": {
        "tns-core-modules": "^3.0.0",
        "tns-platform-declarations": "^3.0.0",
        "typescript": "2.3.4",
        "prompt": "^1.0.0",
        "rimraf": "^2.5.0",
        "tslint": "^5.0.0"
    },
    "dependencies": {
        "nativescript-camera": "^4.0.0",
        "nativescript-fonticon": "^1.1.1",
        "nativescript-iqkeyboardmanager": "^1.2.0",
        "nativescript-loading-indicator": "^2.4.0",
        "nativescript-permissions": "^1.2.3",
        "nativescript-telerik-ui-pro": "^3.1.0-2017.9.11.1"
    },
    "bootstrapper": "nativescript-plugin-seed"
}

**Comment by radeva** [comment]
Hi @fhackenb,

When you started creating the plugin, have you run the postclone step (point 3 [here](https://github.com/NativeScript/nativescript-plugin-seed#tldr)) in order to initialize your plugin? It would also help if you send a tgz file of the plugin so that we can inspect it.

**Comment by fhackenb** [comment]
I believe I ran that step, but I'm not 100% sure. But after trying a couple different things, and still getting that error, I checked and the plugin had actually been installed correctly.
