### ISSUE TITLE
Supporting webpack in your plugin

### ISSUE THREAD

**Issue by radeva** [NativeScript/nativescript-plugin-seed#7]

**Comment by DimitarTachev** [comment]
We could link this article from a next steps section in "Adding Angular Support to UI Plugins".

**Comment by thematan** [comment]
So webpack compilation isn't supported?

I got an error that XXX.ts (the name of the main file with the .android and .ios versions and the one written as 'main' in the package.json) is missing from the typescript compilation. it also happens on a fresh copy of the ng-hello-world template with webpack.
it only works in the demo app, which uses other webpack.config.js than what is defaultly generated (uses awesome-typescript-loader)

couldn't find any mentions for this error in google which is weird
