### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by endymion00** [NativeScript/nativescript-plugin-seed#84]
The section about how to generate typings for iOS includes a link to https://docs.nativescript.org/core-concepts/ios-runtime/how-to/Use-Native-Libraries#troubleshooting which is down.

**Comment by lini** [comment]
Thank you for reporting this. The documentation was updated last week and the link has changed to https://docs.nativescript.org/plugins/Use-Native-iOS-Libraries#troubleshooting 
 I will update the old one in the README.md here.
