### ISSUE TITLE
Pack incompatible with tns version 4.2.1

### ISSUE THREAD

**Issue by Rjgoolsby** [NativeScript/nativescript-plugin-seed#96]
### Make sure to check the demo app(s) for sample usage 
Followed the tutorial here line for line https://docs.nativescript.org/plugins/building-plugins

### Make sure to check the existing issues in this repository 
No issues present

### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

Unable to pack plugin. It ends with this error 

`
nativescript-version-number/publish/src/node_modules/semver/semver.js:310
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 4.2.1
`

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?
 It happens during packing

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
4.2.1

- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)

4.2.0

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
tns-android: 4.0.0
tns-ios: 4.0.0

- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
`{
    "name": "nativescript-version-number",
    "version": "1.0.0",
    "description": "Your awesome NativeScript plugin.",
    "main": "version-number",
    "typings": "index.d.ts",
    "nativescript": {
        "platforms": {
            "android": "4.0.0",
            "ios": "4.0.0"
        }
    },
    "scripts": {
        "tsc": "tsc",
        "build": "npm run tsc && npm run build.native",
        "build.native": "node scripts/build-native.js",
        "postclone": "npm i && node scripts/postclone.js && cd ../demo && npm i && npx rimraf -- package-lock.json && cd ../src",
        "test.android": "npm run tsc && npm run tslint && cd ../demo && tns build android && tns test android --justlaunch",
        "test.ios": "npm run tsc && npm run tslint && cd ../demo && tns build ios && tns test ios --justlaunch",
        "tslint": "cd .. && tslint \"**/*.ts\" --config tslint.json --exclude \"**/node_modules/**\"",
        "plugin.tscwatch": "npm run tsc -- -w",
        "demo.ios": "npm run tsc && cd ../demo && tns run ios --syncAllFiles --emulator",
        "demo.android": "npm run tsc && cd ../demo && tns run android --syncAllFiles --emulator",
        "demo.reset": "cd ../demo && npx rimraf -- hooks node_modules platforms package-lock.json",
        "plugin.prepare": "npm run build && cd ../demo && tns plugin remove nativescript-version-number && tns plugin add ../src",
        "clean": "npm run demo.reset && npx rimraf -- node_modules package-lock.json && npm i",
        "ci.tslint": "npm i && tslint '**/*.ts' --config '../tslint.json' --exclude '**/node_modules/**'",
        "prepack": "npm run build.native"
    },
    "keywords": [
        "NativeScript",
        "JavaScript",
        "Android",
        "iOS"
    ],
    "author": {
        "name": "Your Name",
        "email": "youremail@yourdomain.com"
    },
    "bugs": {
        "url": "https://github.com/Rjgoolsby/nativescript-version-number/issues"
    },
    "license": "Apache-2.0",
    "homepage": "https://github.com/Rjgoolsby/nativescript-version-number",
    "readmeFilename": "README.md",
    "devDependencies": {
        "tns-core-modules": "^4.2.0",
        "tns-platform-declarations": "^4.2.0",
        "typescript": "~2.8.2",
        "prompt": "^1.0.0",
        "rimraf": "^2.6.2",
        "tslint": "^5.11.0",
        "semver": "^5.5.0"
    },
    "dependencies": {},
    "bootstrapper": "nativescript-plugin-seed"
}
`
### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

Simple follow the tutorial

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

Here's proof
in /nativescript-version-number/src/node_modules/semver/semver.js line 302 hardcode the version as4.2.0 (this isn't a fix but just proves the incompatibility) and it runs just fine. If you don't set it then it comes in as 4.2.1 and it throws an invalid version. 

See code below

`
function SemVer(version, loose) {
  if (version instanceof SemVer) {
    if (version.loose === loose)
      return version;
    else
      version = version.version;
  } else if (typeof version !== 'string') {
    throw new TypeError('Invalid Version: ' + version);
  }

  if (version.length > MAX_LENGTH)
    throw new TypeError('version is longer than ' + MAX_LENGTH + ' characters')

  if (!(this instanceof SemVer))
    return new SemVer(version, loose);

  debug('SemVer', version, loose);
  this.loose = loose;
  version = "4.2.0";
  var m = version.trim().match(loose ? re[LOOSE] : re[FULL]);

  if (!m)
    throw new TypeError('Invalid Version: ' + version);

  this.raw = version;

  // these are actually numbers
  this.major = +m[1];
  this.minor = +m[2];
  this.patch = +m[3];

  if (this.major > MAX_SAFE_INTEGER || this.major < 0)
    throw new TypeError('Invalid major version')

  if (this.minor > MAX_SAFE_INTEGER || this.minor < 0)
    throw new TypeError('Invalid minor version')

  if (this.patch > MAX_SAFE_INTEGER || this.patch < 0)
    throw new TypeError('Invalid patch version')

  // numberify any prerelease numeric ids
  if (!m[4])
    this.prerelease = [];
  else
    this.prerelease = m[4].split('.').map(function(id) {
      if (/^[0-9]+$/.test(id)) {
        var num = +id;
        if (num >= 0 && num < MAX_SAFE_INTEGER)
          return num;
      }
      return id;
    });

  this.build = m[5] ? m[5].split('.') : [];
  this.format();
}
`

**Comment by lini** [comment]
The latest NativeScript CLI version is 4.2.3. Can you update your environment and try again?

I tried following the steps in the tutorial and saw no errors when I packed the plugin. Here are the commands I executed:
```bash
git clone https://github.com/NativeScript/nativescript-plugin-seed nativescript-version-number

cd nativescript-version-number/src

npm run postclone

npm run plugin.tscwatch

# in another terminal again in the src directory
npm run demo.android

# stop both commands in the two terminals using Ctrl-C after making sure the demo application works
# then proceed to pack the plugin
cd ../publish
./pack.sh
```

This produces a file called `nativescript-version-number-1.0.0.tgz` in the `publish/package` directory with the packed plugin.

**Comment by Rjgoolsby** [comment]
Ahh. I nailed down the issue. I was reading the error wrong. 

`
   TypeError: Invalid Version: 
   Support for macOS 10.11 is deprecated and will be removed in one of the next releases of 
   NativeScript. Please, upgrade to the latest macOS version.
   4.2.3
`

It's not saying the TNS version is wrong. It's saying my macOS version isn't supported. I'm using my work computer and we haven't been allowed to upgrade to 10.13 (don't ask). I tried this on my personal mac and everything runs just fine. This is an OS issue not plugin issue. Sorry for the inconvenience
